// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9dSqxBez7XeWFsGMkup3AYRXooqgc6E',
    appId: '1:753864294477:web:c72088d88c20ccf8b85c04',
    messagingSenderId: '753864294477',
    projectId: 'ditonton-movie-and-tv',
    authDomain: 'ditonton-movie-and-tv.firebaseapp.com',
    storageBucket: 'ditonton-movie-and-tv.appspot.com',
    measurementId: 'G-GDW17BNF2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDIGWxiVDlM0OczJRT7dC075tBPmXFFao',
    appId: '1:753864294477:android:a8510adda6548ff6b85c04',
    messagingSenderId: '753864294477',
    projectId: 'ditonton-movie-and-tv',
    storageBucket: 'ditonton-movie-and-tv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Ra-OKBfs_Ze5ln39KlDAZRuwhscF2FI',
    appId: '1:753864294477:ios:67f6df2f8df3d9d7b85c04',
    messagingSenderId: '753864294477',
    projectId: 'ditonton-movie-and-tv',
    storageBucket: 'ditonton-movie-and-tv.appspot.com',
    iosClientId: '753864294477-m0d6co0dv1eqjont9ck9qbh9c1qh5rl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );
}
